# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default=b'127.0.0.1')),
                ('port', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[(b'GET', b'GET'), (b'POST', b'POST')], default=b'GET', max_length=4)),
                ('path', models.CharField(default=b'/', max_length=255)),
                ('query_get', models.CharField(default=b'{}', max_length=512)),
                ('query_post', models.CharField(default=b'{}', max_length=512)),
                ('sessionid', models.CharField(default=b'', max_length=512)),
                ('http_referer', models.URLField(default=b'', max_length=1024)),
                ('http_user_agent', models.CharField(default=b'', max_length=255)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
