# Generated by Django 3.2.7 on 2021-09-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='http_referer',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='log',
            name='http_user_agent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4),
        ),
        migrations.AlterField(
            model_name='log',
            name='path',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='query_get',
            field=models.CharField(default='{}', max_length=512),
        ),
        migrations.AlterField(
            model_name='log',
            name='query_post',
            field=models.CharField(default='{}', max_length=512),
        ),
        migrations.AlterField(
            model_name='log',
            name='sessionid',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
