# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 12:51
from __future__ import unicode_literals

import blog.utils
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
        ('blog', '0004_data_migration_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.PositiveIntegerField()),
                ('short_code', models.CharField(max_length=32)),
                ('inst_user', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=blog.utils.get_default_views_count)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('channel', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default=b'', max_length=128)),
                ('image', models.ImageField(max_length=1024, upload_to=b'images')),
                ('front_page', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=0)),
                ('ext_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.InstagramBlog')),
            ],
        ),
        migrations.AddField(
            model_name='instagramcategory',
            name='channels',
            field=models.ManyToManyField(to='blog.InstagramChannel'),
        ),
        migrations.AddField(
            model_name='instagramblog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.InstagramCategory'),
        ),
        migrations.AddField(
            model_name='instagramblog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tag.ArticleTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='instagramblog',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
