# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190305_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramchannel',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instagramcategory',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
