# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190404_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramimage',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
