# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_instagramimage_is_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramblog',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.InstagramChannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=b'instagram_images'),
        ),
    ]
