# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190423_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcategory',
            name='slug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
