# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_instagramcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramimage',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=b'category_images'),
        ),
    ]
