# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190513_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramblog',
            name='inst_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='instagramimage',
            name='inst_id',
            field=models.BigIntegerField(),
        ),
    ]
