# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190514_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramblog',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
