# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True)),
                ('artist', models.CharField(blank=True, default=b'Unknown', max_length=128)),
                ('title', models.CharField(blank=True, default=b'No title', max_length=128)),
                ('lyrics_id', models.CharField(blank=True, max_length=32, null=True)),
                ('genre', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ogg', models.FileField(upload_to=b'radio')),
                ('mp3', models.FileField(upload_to=b'radio')),
                ('url', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
    ]
