# Generated by Django 3.2.7 on 2021-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, default='Unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='mp3',
            field=models.FileField(upload_to='radio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='ogg',
            field=models.FileField(upload_to='radio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=128),
        ),
        migrations.AlterField(
            model_name='audio',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
